### ISSUE TITLE
Wrong Code Generation

### ISSUE THREAD

**Issue by simonabler** [adrianschlatter/ppf.datamatrix#6]
# DataMatrix class does not provide a valid code

## Steps to Reproduce

data = "B|BID|54C64-234F1" 
myDataMatrix = DataMatrix(data)

# Expected Behavior

![barcode](https://user-images.githubusercontent.com/11539504/202434127-b329695c-0184-4c95-9e48-7b79d22da3ab.gif)

# Current Behavior

![bitmap](https://user-images.githubusercontent.com/11539504/202434329-44550310-f279-4f51-95b8-66a706888624.png)

**Comment by adrianschlatter** [comment]
Thanks for reporting this issue. Indeed, the code generated by ppf.datamatrix is invalid. I checked datalog's datamatrix-svg and it generates a readable code. As far as I can tell it generates the code you posted as expected behavior. Looks like I introduced a bug during porting.

I'll gladly look at your solution. I'm not an expert at RS-coding, therefore I'm mainly going to compare it to datalog's encoder. Please have some patience as I need to find some spare time on a weekend to look into this.

**Comment by simonabler** [comment]
Just like me, so I just checked the code of datalog.
I added the reference of the code to the pull request I opened.

https://github.com/datalog/datamatrix-svg/blob/2a678f5a4c45a783c3b024c2df76f36ad32667dc/datamatrix.js#L326

Thanks!
